coverage:
  status:
    patch:
      default:
        target: 100%
        threshold: 0%
    project:
      default:
        informational: true

ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "docs/**/*"
  - "fuzz/**/*"
  - "examples/**/*"
  - "src/pybragerone/cli.py"
  - "src/pybragerone/__main__.py"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true
